// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_xkOeRSGDmcnYWLaGLkmW71Pi7FRe3cA',
    appId: '1:506152736724:web:3ebcb9504d02081b146841',
    messagingSenderId: '506152736724',
    projectId: 'meals-application-eb18b',
    authDomain: 'meals-application-eb18b.firebaseapp.com',
    storageBucket: 'meals-application-eb18b.appspot.com',
    measurementId: 'G-PZ7JHGFH0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzlmURTiOhxXQsQhAinVAll50fPLb3S0I',
    appId: '1:506152736724:android:65631a6ec20cde17146841',
    messagingSenderId: '506152736724',
    projectId: 'meals-application-eb18b',
    storageBucket: 'meals-application-eb18b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj--02s0evBq1TXbIVBcgqA7tPLXbvQ_U',
    appId: '1:506152736724:ios:32b5786b4c98a79d146841',
    messagingSenderId: '506152736724',
    projectId: 'meals-application-eb18b',
    storageBucket: 'meals-application-eb18b.appspot.com',
    iosBundleId: 'com.example.mealsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj--02s0evBq1TXbIVBcgqA7tPLXbvQ_U',
    appId: '1:506152736724:ios:31f127e89bf263be146841',
    messagingSenderId: '506152736724',
    projectId: 'meals-application-eb18b',
    storageBucket: 'meals-application-eb18b.appspot.com',
    iosBundleId: 'com.example.mealsApp.RunnerTests',
  );
}
